version: "3"


networks:
  backend:
    driver: bridge


services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}
    restart: always
    networks:
      - backend
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - documents:/documents
      - ./app:/var/www/my-site
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MEILIKEY=${MEILI_MASTER_KEY}

  db:
    image: mariadb:10.5
    restart: always
    networks:
      - backend
    volumes:
        - database:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD=1

  meilisearch:
    image: getmeili/meilisearch:v1.1.1
    restart: always
    networks:
      backend:
        aliases:
          - document-store-network
    ports:
      - "7700:7700"
    volumes:
      - meilidata:/data.ms
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_LOG_LEVEL=INFO
      - MEILI_DB_PATH=/data.ms
      - MEILI_NO_ANALYTICS=true


volumes:
  documents:
    driver: local
  meilidata:
    driver: local
  database:
    driver: local

