version: "3"


networks:
  backend:
    driver: bridge


services:
  app:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - documents:/documents
      - ./../app:/var/www/my-site
    depends_on:
        - db
    networks:
      - backend
    env_file:
      - ./../.env

  db:
    image: mariadb:10.5
    restart: always
    networks:
      - backend
    volumes:
        - database:/var/lib/mysql
    env_file:
        - ./../.env

  meilisearch:
    image: getmeili/meilisearch
    restart: always
    networks:
      backend:
        aliases:
          - document-store-network
    ports:
      - "7700:7700"
    volumes:
      - meilidata:/data.ms
    environment:
      - MEILI_ENV=production
      - MEILI_NO_ANALYTICS=1
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
      - MEILI_LOG_LEVEL=INFO
      - MEILI_DB_PATH=/data.ms


volumes:
  documents:
    driver: local
  meilidata:
    driver: local
  database:
    driver: local

