version: "3"


networks:
  backend:
    driver: bridge


services:
  app:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - documents:/documents
    depends_on:
        - db
    networks:
      - backend
    env_file:
      - ./../.env

  db:
    image: mariadb:10.5
    restart: always
    networks:
      - backend
    volumes:
        - database:/var/lib/mysql
    env_file:
        - ./../.env

  meilisearch:
    image: getmeili/meilisearch
    restart: always
    networks:
      backend:
        aliases:
          - document-store-network
    ports:
      - "7700:7700"
    volumes:
      - meilidata:/data.ms
    env_file:
      - ./../.env


volumes:
  documents:
    driver: local
  meilidata:
    driver: local
  database:
    driver: local

